# Generated by Django 3.0.2 on 2020-01-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dhaka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('img', models.ImageField(upload_to='dhaka_pic')),
            ],
        ),
    ]
