# Generated by Django 3.0.2 on 2020-01-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0002_chittagong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barishal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('img', models.ImageField(upload_to='bar_pic')),
            ],
        ),
    ]
